#!/usr/bin/env bash
# ============================================================================
# web-host-tool one-command installer
#
# Usage on a fresh (or existing) VPS:
#   curl -fsSL https://raw.githubusercontent.com/KavinduGM/web_host/main/install.sh | sudo bash
#
# Or with the domain pre-set (skips one prompt):
#   curl -fsSL https://raw.githubusercontent.com/KavinduGM/web_host/main/install.sh | sudo bash -s -- demos.example.com
#
# What it does:
#   1. Verifies Docker is installed (installs if missing).
#   2. Clones (or updates) the repo to /opt/web-host-tool.
#   3. Builds the Docker image locally.
#   4. Prompts for: domain, admin password (only the first time).
#   5. Generates JWT_SECRET, bcrypt-hashes the password.
#   6. Creates named docker volumes for demos / db / tenant uploads.
#   7. Detects whether Dokploy/Traefik is already on the box:
#        - If yes  → attaches the container to dokploy-network and adds
#                    Traefik labels so the existing Traefik handles SSL.
#        - If no   → runs a Caddy sidecar bound to :80/:443 with auto-SSL
#                    via Let's Encrypt.
#   8. Starts the container with restart=unless-stopped.
#
# Re-running this script later just updates the deployment (pulls latest
# code, rebuilds, restarts).  Secrets persist in /opt/web-host-tool/.deploy.env.
# ============================================================================
set -euo pipefail

REPO_URL="https://github.com/KavinduGM/web_host.git"
APP_DIR="/opt/web-host-tool"
DEPLOY_ENV="$APP_DIR/.deploy.env"
CONTAINER_NAME="web-host-tool"
CADDY_CONTAINER="web-host-tool-caddy"
IMAGE_NAME="web-host-tool:latest"
INTERNAL_PORT="3001"

# -------- helpers --------------------------------------------------------------
c_red()    { printf '\033[31m%s\033[0m' "$*"; }
c_green()  { printf '\033[32m%s\033[0m' "$*"; }
c_yellow() { printf '\033[33m%s\033[0m' "$*"; }
c_cyan()   { printf '\033[36m%s\033[0m' "$*"; }
step()  { echo; echo "$(c_cyan "==>") $*"; }
ok()    { echo "$(c_green "✓") $*"; }
warn()  { echo "$(c_yellow "!") $*"; }
fail()  { echo "$(c_red "✗") $*"; exit 1; }

need_root() {
  if [ "$EUID" -ne 0 ]; then
    fail "Run with sudo (or as root). Try: curl ... | sudo bash"
  fi
}

# -------- args ----------------------------------------------------------------
DOMAIN_ARG="${1:-}"

# -------- main ----------------------------------------------------------------
need_root

step "Checking Docker"
if ! command -v docker >/dev/null 2>&1; then
  warn "Docker not found — installing"
  curl -fsSL https://get.docker.com | sh
fi
docker info >/dev/null 2>&1 || fail "Docker is installed but not running. Start it with: systemctl start docker"
ok "Docker OK ($(docker --version))"

step "Fetching source"
if [ ! -d "$APP_DIR/.git" ]; then
  git clone --depth 1 "$REPO_URL" "$APP_DIR"
  ok "Cloned $REPO_URL → $APP_DIR"
else
  (cd "$APP_DIR" && git fetch --depth 1 origin main && git reset --hard origin/main)
  ok "Pulled latest from $REPO_URL"
fi
LATEST_COMMIT=$(cd "$APP_DIR" && git log -1 --format='%h %s')
echo "    Latest commit: $LATEST_COMMIT"

# -------- collect or load deployment secrets ----------------------------------
if [ -f "$DEPLOY_ENV" ]; then
  step "Reusing existing deployment config from $DEPLOY_ENV"
  # shellcheck disable=SC1090
  set -a; . "$DEPLOY_ENV"; set +a
  ok "Domain:   $DOMAIN"
  ok "Mode:     $DEPLOY_MODE"
else
  step "First-time setup"

  DOMAIN="${DOMAIN_ARG:-}"
  if [ -z "$DOMAIN" ]; then
    read -rp "Domain (e.g. demos.example.com): " DOMAIN < /dev/tty
  fi
  [ -n "$DOMAIN" ] || fail "Domain is required"

  # Admin password — read silently
  while true; do
    read -rsp "Admin password (min 8 chars): " PW1 < /dev/tty; echo
    [ "${#PW1}" -ge 8 ] || { warn "Too short — try again"; continue; }
    read -rsp "Confirm password: " PW2 < /dev/tty; echo
    [ "$PW1" = "$PW2" ] && break
    warn "Passwords don't match — try again"
  done

  # Generate JWT + bcrypt hash
  step "Generating secrets"
  JWT_SECRET=$(openssl rand -hex 32)
  HASH=$(docker run --rm -e PW="$PW1" -w /tmp node:20-bookworm-slim bash -c \
    'echo "{}" > package.json && npm install bcryptjs >/dev/null 2>&1 && node -e "console.log(require(\"bcryptjs\").hashSync(process.env.PW, 10))"')
  unset PW1 PW2
  [ -n "$HASH" ] || fail "Failed to hash password"
  ok "Secrets generated"

  # Detect deploy mode
  if docker network inspect dokploy-network >/dev/null 2>&1; then
    DEPLOY_MODE="traefik"
    ok "Detected Dokploy/Traefik network → will attach to dokploy-network"
  else
    DEPLOY_MODE="caddy"
    ok "No Traefik detected → will run standalone with Caddy + Let's Encrypt"
  fi

  # Persist
  install -d -m 700 "$APP_DIR"
  cat > "$DEPLOY_ENV" <<EOF
# Generated by install.sh on $(date -Is)
# Edit carefully — these power the container's runtime config.
DOMAIN=$DOMAIN
DEPLOY_MODE=$DEPLOY_MODE
JWT_SECRET=$JWT_SECRET
ADMIN_PASSWORD_HASH='$HASH'
EOF
  chmod 600 "$DEPLOY_ENV"
  ok "Saved deployment config to $DEPLOY_ENV (mode 600)"
fi

# -------- build image ---------------------------------------------------------
step "Building image $IMAGE_NAME (this can take 1-3 min)"
(cd "$APP_DIR" && docker build --pull -t "$IMAGE_NAME" .)
ok "Image built"

# -------- volumes -------------------------------------------------------------
step "Ensuring named volumes exist"
for v in web_host_demos web_host_state web_host_tenants; do
  docker volume inspect "$v" >/dev/null 2>&1 || docker volume create "$v" >/dev/null
done
ok "Volumes ready: web_host_demos, web_host_state, web_host_tenants"

# -------- start container -----------------------------------------------------
step "Stopping any previous container"
docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
docker rm -f "$CADDY_CONTAINER" >/dev/null 2>&1 || true

PUBLIC_BASE_URL="https://$DOMAIN"

case "$DEPLOY_MODE" in
  traefik)
    step "Starting container behind Dokploy's Traefik"
    docker run -d \
      --name "$CONTAINER_NAME" \
      --restart unless-stopped \
      --network dokploy-network \
      -v web_host_demos:/data/demos \
      -v web_host_state:/data/state \
      -v web_host_tenants:/data/tenants \
      -e JWT_SECRET="$JWT_SECRET" \
      -e ADMIN_PASSWORD_HASH="$ADMIN_PASSWORD_HASH" \
      -e PUBLIC_BASE_URL="$PUBLIC_BASE_URL" \
      --label "traefik.enable=true" \
      --label "traefik.docker.network=dokploy-network" \
      --label "traefik.http.routers.web-host-tool.rule=Host(\`$DOMAIN\`)" \
      --label "traefik.http.routers.web-host-tool.entrypoints=websecure" \
      --label "traefik.http.routers.web-host-tool.tls=true" \
      --label "traefik.http.routers.web-host-tool.tls.certresolver=letsencrypt" \
      --label "traefik.http.services.web-host-tool.loadbalancer.server.port=$INTERNAL_PORT" \
      "$IMAGE_NAME" >/dev/null
    ok "Container $CONTAINER_NAME running and attached to dokploy-network"
    ;;

  caddy)
    step "Starting container + Caddy auto-SSL"
    # App container — bound only to the dedicated bridge network, no host ports
    docker network inspect web-host-net >/dev/null 2>&1 || docker network create web-host-net >/dev/null
    docker run -d \
      --name "$CONTAINER_NAME" \
      --restart unless-stopped \
      --network web-host-net \
      -v web_host_demos:/data/demos \
      -v web_host_state:/data/state \
      -v web_host_tenants:/data/tenants \
      -e JWT_SECRET="$JWT_SECRET" \
      -e ADMIN_PASSWORD_HASH="$ADMIN_PASSWORD_HASH" \
      -e PUBLIC_BASE_URL="$PUBLIC_BASE_URL" \
      "$IMAGE_NAME" >/dev/null

    # Caddy with a generated Caddyfile
    CADDY_DIR="$APP_DIR/.caddy"
    mkdir -p "$CADDY_DIR"
    cat > "$CADDY_DIR/Caddyfile" <<EOF
$DOMAIN {
  encode gzip zstd
  reverse_proxy $CONTAINER_NAME:$INTERNAL_PORT
}
EOF
    docker run -d \
      --name "$CADDY_CONTAINER" \
      --restart unless-stopped \
      --network web-host-net \
      -p 80:80 -p 443:443 -p 443:443/udp \
      -v "$CADDY_DIR/Caddyfile:/etc/caddy/Caddyfile:ro" \
      -v web_host_caddy_data:/data \
      -v web_host_caddy_config:/config \
      caddy:2 >/dev/null
    ok "Caddy running on :80/:443 — first request will auto-provision SSL"
    ;;

  *)
    fail "Unknown DEPLOY_MODE: $DEPLOY_MODE"
    ;;
esac

# -------- wait for health -----------------------------------------------------
step "Waiting for container to become healthy"
for i in $(seq 1 30); do
  if docker exec "$CONTAINER_NAME" wget -qO- "http://127.0.0.1:$INTERNAL_PORT/health" >/dev/null 2>&1; then
    ok "App responded on /health after ${i}s"
    break
  fi
  sleep 1
  if [ "$i" = "30" ]; then
    warn "App didn't respond within 30s — check: docker logs $CONTAINER_NAME"
  fi
done

# -------- done ----------------------------------------------------------------
echo
echo "=============================================================="
echo "$(c_green '✓ web-host-tool is deployed')"
echo "=============================================================="
echo "Admin panel:    $PUBLIC_BASE_URL/admin"
echo "Deploy mode:    $DEPLOY_MODE"
echo "Container:      $CONTAINER_NAME"
echo "Config file:    $DEPLOY_ENV"
echo
echo "Useful commands:"
echo "  Logs:         docker logs -f $CONTAINER_NAME"
echo "  Restart:      docker restart $CONTAINER_NAME"
echo "  Update:       bash $APP_DIR/install.sh   # re-run this script"
echo "  Reset admin:  rm $DEPLOY_ENV && bash $APP_DIR/install.sh"
echo "=============================================================="
